### PR TITLE
[Fix-436] years direction and layout in TextView

### LINKED ISSUE #436: [Bug] Text view - direction on years rang is wrong in hebrew
**Describe the bug**
Numbers in hebrew sentence should be written from right to left.
משעה/ שנה עד שעה/ שנה.

**Screenshots**

### PR DESCRIPTION
**Pull request by yaeluria**
use 'in' instead of 'between', fix direction for years, and display text and years on same line, closes #436

### CODE REVIEW

File: src/components/molecules/TextView.tsx [hunk 1]
```diff
@@ -72,23 +72,15 @@ const TextView: FC<IProps> = ({ data, segmentText }) => {
...
-              <Typography.Body1>{t('textView.betweenYears')}</Typography.Body1>
-            </Box>
-            <Box mr={1}>
-              <Typography.Body1>
-                {items.end_year} - {items.start_year}{' '}
-              </Typography.Body1>
-            </Box>{' '}
+            <Typography.Body1>{t('textView.inYears')} </Typography.Body1>
+            <Typography.Body1>
+              {items.start_year} - {items.end_year}{' '}
```
Comment (yuvalbl) [inline src/components/molecules/TextView.tsx:82]: remove space

**Review by yuvalbl — APPROVED** [review]
