### PR TITLE
Bug 677 text display in map widget image

### LINKED ISSUE #677: [Bug] Last updated date on the map widget is curropted
Steps to reconstruct:
1. go to homepage
2. go to map card
3. download as image
4. open image locally on your machine and see date text is messed up:

image

most_severe_accidents (15)

### PR DESCRIPTION
**Pull request by daniel-ilan**
Closes #677 - see issue for further details

1. Changed text to render in svg <text> tag

### CODE REVIEW

File: src/components/molecules/card/CardFooter.tsx [hunk 1]
```diff
@@ -20,16 +21,26 @@ const useStyles = makeStyles({
...
   },
 });
 
 const CardFooter: React.FC<IProps> = ({ dateComment }) => {
   const classes = useStyles();
+  const store = useStore();
+  const [xPosition, setXPosition] = useState(300);
+  useEffect(() => {
+    setXPosition(store.currentLanguageRouteString === '/en' ? 0 : 300);
+  }, [store.currentLanguageRouteString]);
```
Comment (yuvalbl) [inline src/components/molecules/card/CardFooter.tsx:34]:
```suggestion
const xPosition = store.currentLanguageRouteString === '/en' ? 0 : 300
```

Comment (daniel-ilan) [reply src/components/molecules/card/CardFooter.tsx]: I changed the file to use only html-to-canvas and there is no need for SVG tag anymore

File: src/components/molecules/card/CardFooter.tsx [hunk 2]
```diff
@@ -20,17 +20,16 @@ const useStyles = makeStyles({
     justifyContent: 'flex-end',
   },
   comment: {
```
Comment (yuvalbl) [inline src/components/molecules/card/CardFooter.tsx:22]: seems like this class in unused

**Review by yuvalbl — APPROVED** [review]
